<a href="https://colab.research.google.com/github/Subhranshu-123/BIKE2/blob/main/Another_copy_of_subhranshu_sekhar_pani.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Numpy

A powerful library for numerical computations in Python.

NumPy vectorization, indexing, and broadcasting concepts are the de-facto standards of array computing.

Offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.



How to install Numpy

In [1]:
!pip install numpy

To use Numpy, we first need to import the `numpy` package:

In [2]:
import numpy as np

###Arrays

* An array is a structured way of storing and retrieving data, often
visualized as a grid where each cell contains one data element.

* a NumPy array is a grid of values, all of the same type, indexed by a tuple of nonnegative integers.

* The number of dimensions is called the rank of the array, and its shape is a tuple of integers that specifies the size of the array along each dimension.

For example, a one-dimensional array can be visualized like a list, with each element of the list representing a cell in the array.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [3]:
a = np.array([1,2,3,4,5])  # Create a  1D array
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)



<class 'numpy.ndarray'> (5,) 1 2 3
[5 2 3 4 5]


In [4]:
b = np.array([[1,2,3],[4,5,6]])   # Create a 2D array
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


Numpy also provides many functions to create arrays:

In [6]:
a = np.zeros((3,2))  # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [7]:
b = np.ones((3,2))   # Create an array of all ones
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
c = np.full((3,2), 5) # Create an array with values 5

print(c)

[[5 5]
 [5 5]
 [5 5]]


In [9]:
c = np.full((3,2), 7) # Create an array with values 7

print(c)

[[7 7]
 [7 7]
 [7 7]]


In [10]:
d = np.eye(4)        # Create a 2x2 identity matrix
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)



[[0.50719361 0.56023074]
 [0.38959524 0.59916379]]


# Question

Given the following array:


a = np.array([1, 2, 3, 4, 5])

Q1 Replace First and Last Element

Q2 Sum All Elements in a 2D Array

Q3 What is the shape of this array?

Q4 What is the value at index 2?

Q5Create a Custom Matrix with All 7s


In [12]:
#1 answer
a = np.array([1, 2, 3, 4, 5])
a[0]=5
print(a)
a[-1]=22
print(a)


[5 2 3 4 5]
[ 5  2  3  4 22]


In [13]:
#3 answer
a.shape

(5,)

In [14]:
#4 answer
a[1]
a[2]
print(a[1],a[2])

2 3


In [15]:
#5 answer
c = np.full((3,2), 7) # Create an array with values 7

print(c)

[[7 7]
 [7 7]
 [7 7]]


In [16]:
#2 answer
b = np.array([[1,2,3],
 [4,5,6]])   # Create a 2D array
print(b)
print(sum(b))
print(np.sum(b))

[[1 2 3]
 [4 5 6]]
[5 7 9]
21


###Array indexing

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [17]:
import numpy as np

# Create the following 2D array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[0:2, 1:3]   # row 0,1, column  1,2,
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[2 3]
 [6 7]]


###Assignment: Given array extract the middle four element as 2D array and print it. Output: [
                    [6,7],
                    [10,11] ]

###$ Print the slice format a[x:y, p:q]  

In [18]:
#answer
b=a[1:3,1:3]
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 6  7]
 [10 11]]


A slice of an array is a view into the same data, so modifying it will modify the original array.

In [19]:
#practice
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])

2
2


In [20]:
#practice
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 0])

2
1


In [21]:
#practice
print(a[0, 1])
b[1, 1] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[1, 1])

2
77


In [22]:
print(a[0, 1])
b[0, 1] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])

2
2


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array.

In [23]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [1,2,3,4]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]


In [24]:
#pracctice
print(a>12)
print(a>11)
print(a[a>6])

[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]
[[False False False False]
 [False False False False]
 [False False False  True]
 [False False False False]]
[ 7  8  9 10 11 12]


Two ways of accessing the data in the middle row of the array.
Mixing integer indexing with slices yields an array of lower rank,
while using only slices yields an array of the same rank as the
original array:

In [25]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [26]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10  2] (4,)

[[ 2]
 [ 6]
 [10]
 [ 2]] (4, 1)


Integer array indexing: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [27]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]]) # Here besically we are looking int array values of a[0,0],a[1, 1], a[2, 0]

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


In [28]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [29]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [30]:
print(np.arange(4)) # Its like range(4)

[0 1 2 3]


In [31]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of b using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

[ 1  6  7 11]


In [32]:
b=np.array([0,2,0])
print(a[np.arange(3),b])

[1 6 7]


In [33]:
b=np.array([0,2,0])
print(a[np.arange(3),b])

[1 6 7]


In [34]:
# Mutate one element from each row of a using the indices in b
b = np.array([0, 2, 0, 1])
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


# Question


# Given the 2D array:
a = np.array([[10, 20, 30, 40],
              [50, 60, 70, 80],
              [90,100,110,120]])

# Task:
# 1. Extract a subarray b containing:
#       [[20, 30],
#        [60, 70]]
# 2. Set b first element value to 999
# 3. Print both `a` and `b`



In [35]:
#answer
a = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90,100,110,120]])
b=a[0:2,1:3]
print(a)
print(b)


[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
[[20 30]
 [60 70]]


In [36]:
#anser 2 and 3
a = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90,100,110,120]])
b=a[0:2,1:3]
b[0,0]=999
print(a)
print(b)

[[ 10 999  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
[[999  30]
 [ 60  70]]


Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [37]:
import numpy as np



a = np.array([[0,2], [3, 4], [5, 6]])

bool_idx = (a>0)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

[[False  True]
 [ True  True]
 [ True  True]]


In [38]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
#print(a[bool_idx])
#print(a)
# We can do all of the above in a single concise statement:
print(a[a <=2])

[0 2]


###Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [39]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


In [40]:
x=np.array([[1,2,3,4],[5,6,7,8],[1,2,3,4],[3,4,5,6]])
#print(x)

x[:,:]=5
print(x)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [41]:
#practice1
x=np.array([[1,2,3,4],[5,6,7,8],[1,2,3,4],[3,4,5,6]])
x[:,:]=6
print(x)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


###Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [42]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x)
print(y)

# Elementwise sum; both produce the array
print(x + y)
#print(np.add(x, y))

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[ 6.  8.]
 [10. 12.]]


In [43]:
# Elementwise difference; both produce the array
print(y - x)
print(np.subtract(x, y))

[[4. 4.]
 [4. 4.]]
[[-4. -4.]
 [-4. -4.]]


 We use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [44]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(np.dot(w,v))
#print(np.dot(v, w))

219


# question

# a ={5,9,11,21,23}
# b={3,21,31,33,43}

 # c=a+b
# find the elementwise sum of a and b  in  c={8, 30,}

# Find dot produce of a, c and a, a

# Use reshape to do the same dot product.

# 1. Create two 1D vectors:
#    v = np.array([9, 10])
#    w = np.array([11, 12])
# 2. Compute the inner product using:
#    a. `np.dot(v, w)`
#    b. `np.dot(w, v)`
# 3. write function to verify both are equal or not

In [45]:
#1 answer
a =np.array([5,9,11,21,23])
b=np.array([3,21,31,33,43])
c=a+b
print(c)

[ 8 30 42 54 66]


In [46]:
#2 and 3 answer
v = np.array([9, 10])
w = np.array([11, 12])
print(np.dot(v,w))
print(np.dot(w,v))# both are equal
print(np.dot(v,w)==np.dot(w,v))

219
219
True


You can also use the `@` operator which is equivalent to numpy's `dot` operator.

In [47]:
print(v @ w)

219


In [48]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

[29 67]
[29 67]
[29 67]


In [49]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [50]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Besides computing mathematical functions with arrays, we often need to reshape or manipulate the data within them. A simple example of this type of operation is transposing a matrix. To transpose a matrix, simply use the T attribute of an array object.

In [51]:
print(x)
print("transpose\n", x.T)

[[1 2]
 [3 4]]
transpose
 [[1 3]
 [2 4]]


In [52]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


# Question
Create two 2x2 matrices and perform:

Addition

Multiplication

Transpose

Verify if
$$A^T.B = A.B^T$$


In [53]:
#answer
x=np.array([[5,6],[7,8]])
y=(np.sum(x))
z=(np.sum(x,axis=0))
w=(np.sum(x,axis=1))
print(x)
print(y)
print(z)
print(w)



[[5 6]
 [7 8]]
26
[12 14]
[11 15]


In [54]:
#answer
print(x)
print("transpose\n", x.T)

[[5 6]
 [7 8]]
transpose
 [[5 7]
 [6 8]]


In [55]:
#answer
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[8,9]])
x=np.dot(a,b)
print(x)
# or
print(a@b)
#or
print(a.dot(b))

[[21 24]
 [47 54]]
[[21 24]
 [47 54]]
[[21 24]
 [47 54]]


# Inverse and Identity Matrix

In [56]:

A = np.array([[1, 2], [3, 4]])
I = np.eye(2)
A_inv = np.linalg.inv(A)

print(I)
print(A_inv)

[[1. 0.]
 [0. 1.]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [57]:
#practice1
A = np.array([[4, 3], [5, 6]])
I = np.eye(2)
A_inv = np.linalg.inv(A)
print(I)
print(A_inv)

[[1. 0.]
 [0. 1.]]
[[ 0.66666667 -0.33333333]
 [-0.55555556  0.44444444]]


###Broadcasting

Broadcasting is a powerful mechanism in NumPy that enables it to perform arithmetic operations on arrays with different shapes. Often, we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform operations on the larger array.

For example, if we want to add a constant vector to each row of a matrix, we can achieve this as follows:

In [58]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [59]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [60]:
y = x + vv  # Add x and vv elementwise
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [61]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

rule for broadcasting:
You can do these arithmetic operations on matrices of different sizes, but only if one matrix has only one column or one row.



Here are some applications of broadcasting:

In [62]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [63]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

[[2 4 6]
 [5 7 9]]


In [64]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [65]:
import pandas as pd
a={'number':[1,2,3,4,5]}
d=pd.DataFrame(a)

In [66]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [67]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)




[[ 2  4  6]
 [ 8 10 12]]


Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

##Pandas

# practice question

# 📘 Linear Algebra Practice with Python


# Q1: Vector Addition
# Write a function to add two vectors.
def add_vectors(v1, v2):
    pass  # TODO: return element-wise sum

# Q2: Dot Product
# Compute the dot product of two vectors without using numpy.dot.
def dot_product(v1, v2):
    pass  # TODO: multiply element-wise and sum

# Q3: Matrix Transpose
# Transpose a matrix using a nested list.
def transpose(matrix):
    pass  # TODO: return transposed matrix

# Q4: Matrix Multiplication
# Multiply two 2x2 matrices using nested loops.
def multiply_matrices(A, B):
    pass  # TODO: implement matrix multiplication

# Q5: Identity Matrix
# Create an identity matrix of size n using NumPy.
import numpy as np
def identity_matrix(n):
    pass  

# Q6: Determinant of 2x2 or 3x3 matrix
# Compute determinant without using numpy.linalg.det
def determinant(matrix):
    pass  # TODO: handle 2x2 and 3x3 cases

# Q7: Eigenvalues and Eigenvectors
# Use NumPy to compute eigenvalues and eigenvectors.
def eigen_properties(matrix):
    pass  # TODO: use np.linalg.eig

# Q8: Solve Linear System Ax = b
# Solve using numpy.linalg.solve
def solve_linear_system(A, b):
    pass


# Q11: Projection of Vector a onto b
def projection(a, b):
    pass  # TODO: use projection formula


# Q12: Norm of a Vector
# Compute L1, L2, and Infinity norm of a vector
def vector_norms(v):
    pass  # TODO: use np.linalg.norm with ord=1, 2, np.inf

# Q13: Normalize a Vector
# Convert a vector to a unit vector
def normalize_vector(v):
    pass  # TODO: divide by its L2 norm


# Q14: Check Symmetric Matrix
# Verify if a matrix is symmetric
def is_symmetric(matrix):
    pass  

# Q15: Inverse of a Matrix
# Compute the inverse of a square matrix
def inverse_matrix(matrix):
    pass  

# Q16 Find the inverse of a matrix and validate
 A * A⁻¹ = I




In [68]:
# 1
v1=np.array([1,2,3])
v2=np.array([4,5,6])
def Vect_add(v1,v2):
  if len(v1)!=len(v2):
    print('error!')
  r=[x+y for x,y in zip(v1,v2)]
  return v1+v2
  vect_add(v1,v2)
print(Vect_add(v1,v2))

[5 7 9]


In [69]:
#2
v1=np.array([1,2,3])
v2=np.array([4,5,6])
def dot_add(v1,v2):
  if len(v1)!=len(v2):
    print('error!')
  r=[x*y for x,y in zip(v1,v2)]
  return v1*v2
  dot_add(v1,v2)
print(dot_add(v1,v2))

[ 4 10 18]


In [71]:
#3
matrix=np.array([[1,2,3],[4,5,6]])
def transpose_matrix(matrix):
  rows=len(matrix)
  columns=len(matrix[0])
  transpose=[[0 for _ in range(rows)] for _ in range(columns)]
  for i in range(rows):
    for j in range( columns):
      transpose[j][i]=matrix[i][j]
  return transpose
  transpose_matrix(matrix)
print(transpose_matrix(matrix))


[[np.int64(1), np.int64(4)], [np.int64(2), np.int64(5)], [np.int64(3), np.int64(6)]]


In [76]:
#4
matrix_1= np.array([[1,2,3],[4,5,6]])
matrix_2=np.array([[7,8],[9,10],[11,12]])
def matrix_multiply(matrix_1,matrix_2):
  rows_1=len(matrix_1)
  column_1=len(matrix_1[0])
  rows_2=len(matrix_2)
  column_2=len(matrix_2[0])
  if column_1!=rows_2:
    print('error!')
  result=[[0 for _ in range(column_2)] for _ in range (rows_1)]
  for i in range(rows_1):
    for j in range(column_2):
      for k in range(column_1):
        result[i][j]+=matrix_1[i][k]*matrix_2[k][j]
  return result
  product=matrix_multiply(matrix_1,matrix_2)
print(matrix_multiply(matrix_1,matrix_2))



[[np.int64(58), np.int64(64)], [np.int64(139), np.int64(154)]]


In [78]:
#5
import numpy as np
identify_matrix=np.eye(4)
print(identify_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [89]:
#6(a) 2x2
import numpy as np
a= np.array([[3,2],[7,8]])


def determinant_(matrix):
 if len(matrix)!=2 or any(len(row)!= 2 for row in matrix):
   raise TypeError('input error!')
 a=matrix[0][0]
 b=matrix[0][1]
 c=matrix[1][0]
 d=matrix[1][1]
 return(a*d-b*c)
 product=determinant_(matrix)
print(determinant_(a))

10


In [97]:
#6 (b) 3x3
matrix=[
      [1,2,3],
      [4,5,6],
      [9,7,8]
 ]
def determinant_(matrix):
  det=(matrix[0][0]*(matrix[1][1]*matrix[2][2]-matrix[1][2]*matrix[2][1])-
       matrix[0][1]*(matrix[1][0]*matrix[2][2]-matrix[1][2]*matrix[2][0])+
       matrix[0][2]*(matrix[1][0]*matrix[2][1]-matrix[1][1]*matrix[2][0]))
  return det

  determinant=determinant_(matrix)
print(determinant_(matrix))

-9


In [102]:
#7
import numpy as np
A = np.array([[1, 3],[4, 5]])
Eigen_values,Eigen_vectors = np.linalg.eig(A)
print(f'Eigenvalues:{Eigen_values}')
print(f'Eigenvectors :{Eigen_vectors}')

Eigenvalues:[-1.  7.]
Eigenvectors :[[-0.83205029 -0.4472136 ]
 [ 0.5547002  -0.89442719]]


In [103]:
#8
import numpy as np
a=np.array([[1,3],[14,17]])
b=np.array([4,7])
x= np.linalg.solve(a,b)
print(x)

[-1.88  1.96]


In [106]:
#11
#projection=((a.b)/b^2)b
import numpy as np
a=[2,4]
b=[3,5]
def vector_projection(a,b):
  a=np.array(a)
  b=np.array(b)
  projection=(np.dot(a,b)/np.dot(b,b))*b
  return projection
  projection=vector_projection(a,b)
print(vector_projection(a,b))

[2.29411765 3.82352941]


In [125]:
#12norm i1= sum of absolute value of elements
#x[1,2,_3]=6
# norm l2= square root of elements
#[1,2,-3]=|1,4,9|=|14|=root over 14=3.75
#inorm l3= max absolute values of elements
# 1,2,-3=3
import numpy as np
def compute_norms(vector):
  L1_norm=np.linalg.norm(vector,ord=1)
  L2_norm=np.linalg.norm(vector,ord=2)
  Linf_norm=np.linalg.norm(vector,ord=np.inf)
  return L1_norm,L2_norm,Linf_norm
  vector = np.array([1,2,-3])
  L1 ,L2 ,L3 = compute_norms(vector)
print(f'L1 norm :{L1}')
print(f'L2 norm :{L2}')
print(f'l3 norm :{L3}')



L1 norm :6.0
L2 norm :3.7416573867739413
l3 norm :3.0


In [126]:
#13
#u/|v|
#|v|=sqre root(x^2+y^2+z^2)
import numpy as np
def unit_vector(vector):
  magnitude=np.linalg.norm(vector)
  unit_vector=vector/magnitude
  return unit_vector
  vector=np.array([4,5,6])
  unit_vectoR=unit_vector(vector)
print(unit_vector(vector))

[ 0.26726124  0.53452248 -0.80178373]


In [144]:
#14 symmetric matrix
#when A transpose= A,A[i][j]=A[j][i]
import numpy as np
def create_symmetric_matrix(n):
    matrix=np.random.rand(n,n)
    symmetric_matrix=(matrix+matrix.T)/2
    return symmetric_matrix
n=3
symmetric_matrix=create_symmetric_matrix(n)
print(symmetric_matrix)

[[0.26380791 0.61957398 0.36932358]
 [0.61957398 0.51983807 0.45108396]
 [0.36932358 0.45108396 0.70898793]]


In [145]:
#15 inverse of matrix
import numpy as np
matrix = np.array([[2,4],[5,6]])
inverse_matrix=np.linalg.inv(matrix)
print('original matrix :')
print(matrix)
print(inverse_matrix)

original matrix :
[[2 4]
 [5 6]]
[[-0.75   0.5  ]
 [ 0.625 -0.25 ]]


In [146]:
#A * A⁻¹ = I(identity matrix)
import numpy as np
matrix = np.array([[2,4],[5,6]])
inverse_matrix=np.linalg.inv(matrix)
I=np.identity(matrix.shape[0])
result=np.matmul(matrix,inverse_matrix)
print(result)
print(I)

[[ 1.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00]]
[[1. 0.]
 [0. 1.]]
