<a href="https://colab.research.google.com/github/Subhranshu-123/BIKE2/blob/main/Copy_of_PROGRAMMING_MID_TERM_ASSESSMENT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

A.PYTHON BASICS(LIST,TUPLE,DICTIONARIES)

In [ ]:
# Create a list of 10 integers
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Calculate and print sum
print(f"Sum: {sum(numbers)}")

# Calculate and print average
print(f"Average: {sum(numbers) / len(numbers)}")

# Calculate and print maximum
print(f"Maximum: {max(numbers)}")

# Calculate and print minimum
print(f"Minimum: {min(numbers)}")

Sum: 55
Average: 5.5
Maximum: 10
Minimum: 1


In [ ]:
# Create a tuple of 5 city names
city_names = ("London", "Paris", "Rome", "Tokyo", "Berlin")

# Print the tuple in reverse order using slicing
print(f"Original Tuple: {city_names}")
print(f"Reversed Tuple: {city_names[::-1]}")


Original Tuple: ('London', 'Paris', 'Rome', 'Tokyo', 'Berlin')
Reversed Tuple: ('Berlin', 'Tokyo', 'Rome', 'Paris', 'London')


In [ ]:
# Create a list with duplicate numbers
numbers_with_duplicates = [10, 20, 10, 30, 40, 20, 50, 40]

# Convert the list to a set to remove duplicates (sets store only unique elements)
unique_numbers_set = set(numbers_with_duplicates)

# Convert the set back to a list (optional, if you need a list as output)
unique_numbers_list = list(unique_numbers_set)

print(f"Original List: {numbers_with_duplicates}")
print(f"List with Duplicates Removed: {unique_numbers_list}")

Original List: [10, 20, 10, 30, 40, 20, 50, 40]
List with Duplicates Removed: [40, 10, 50, 20, 30]


In [ ]:
# Create a dictionary of student names and marks
student_marks = {
    "Alice": 85,
    "Bob": 92,
    "Charlie": 78,
    "David": 92,
    "Eve": 89,
}

# Find the student(s) with the highest marks
max_marks = 0
highest_achievers = []

for student, marks in student_marks.items():
    if marks > max_marks:
        max_marks = marks
        highest_achievers = [student]  # Start a new list if a new max is found
    elif marks == max_marks:
        highest_achievers.append(student)  # Add to existing list if marks are tied

print(f"Student Marks: {student_marks}")
print(f"Student(s) with the highest marks: {highest_achievers}")


Student Marks: {'Alice': 85, 'Bob': 92, 'Charlie': 78, 'David': 92, 'Eve': 89}
Student(s) with the highest marks: ['Bob', 'David']


In [ ]:
# Define the string
my_string = "programming"

# Create an empty dictionary to store character frequencies
char_frequency = {}

# Iterate through each character in the string
for char in my_string:
    # If the character is already in the dictionary, increment its count
    if char in char_frequency:
        char_frequency[char] += 1
    # If the character is not in the dictionary, add it with a count of 1
    else:
        char_frequency[char] = 1

print(f"String: '{my_string}'")
print(f"Character Frequency: {char_frequency}")


String: 'programming'
Character Frequency: {'p': 1, 'r': 2, 'o': 1, 'g': 2, 'a': 1, 'm': 2, 'i': 1, 'n': 1}


B.FILE OPERATION

In [ ]:
# Create a text file named data.txt and write 5 lines of text into it.
file_name = "data.txt"
lines_to_write = [
    "This is line 1.\n",
    "This is line 2.\n",
    "This is line 3.\n",
    "This is line 4.\n",
    "This is line 5.\n"
]

with open(file_name, 'w') as file:
    file.writelines(lines_to_write)
print(f"File '{file_name}' created and 5 lines written.")


File 'data.txt' created and 5 lines written.


In [ ]:
# Read all lines from data.txt and print them one by one.
file_name = "data.txt"

try:
    with open(file_name, 'r') as file:
        print(f"\nContents of '{file_name}':")
        for line in file:
            print(line.strip()) # .strip() removes leading/trailing whitespace, including the newline character
except FileNotFoundError:
    print(f"File '{file_name}' not found.")



Contents of 'data.txt':
This is line 1.
This is line 2.
This is line 3.
This is line 4.
This is line 5.


In [ ]:
# Modify the program above to count the number of words in data.txt.
file_name = "data.txt"
word_count = 0

try:
    with open(file_name, 'r') as file:
        content = file.read()
        words = content.lower().split() # Split by whitespace and convert to lowercase for accurate counting
        word_count = len(words)
    print(f"\nTotal number of words in '{file_name}': {word_count}")
except FileNotFoundError:
    print(f"File '{file_name}' not found.")



Total number of words in 'data.txt': 20


In [ ]:
# Write a program that reads a file and counts how many times a given word (e.g., 'Python') appears in it.
file_name = "data.txt"
target_word = "Python"
occurrence_count = 0

try:
    with open(file_name, 'r') as file:
        content = file.read().lower() # Read and convert to lowercase for case-insensitive search
        occurrence_count = content.count(target_word.lower())
    print(f"\nThe word '{target_word}' appears {occurrence_count} times in '{file_name}'.")
except FileNotFoundError:
    print(f"File '{file_name}' not found.")



The word 'Python' appears 0 times in 'data.txt'.


In [ ]:
# Write a Python program that copies the contents of one file into another file.
import shutil

source_file = "data.txt"
destination_file = "data_copy.txt"

try:
    shutil.copyfile(source_file, destination_file)
    print(f"\nContents of '{source_file}' copied to '{destination_file}'.")
except FileNotFoundError:
    print(f"Source file '{source_file}' not found.")



Contents of 'data.txt' copied to 'data_copy.txt'.


C.NUMPY

In [ ]:
# Write a NumPy program to create a 1D array of numbers from 1 to 20 and print only the even numbers.
import numpy as np

# Create a 1D array of numbers from 1 to 20
arr = np.arange(1, 21)

# Print only the even numbers
even_numbers = arr[arr % 2 == 0]
print(f"\nEven numbers from 1 to 20: {even_numbers}")



Even numbers from 1 to 20: [ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
# Create a 3x3 NumPy array filled with random integers between 1 and 50. Find the maximum and minimum values.
import numpy as np

# Create a 3x3 array with random integers between 1 and 50
random_array = np.random.randint(1, 51, size=(3, 3))
print(f"\n3x3 Random Array:\n{random_array}")

# Find maximum and minimum values
max_value = random_array.max()
min_value = random_array.min()
print(f"Maximum value: {max_value}")
print(f"Minimum value: {min_value}")



3x3 Random Array:
[[34  3  8]
 [26  9 41]
 [48 18 49]]
Maximum value: 49
Minimum value: 3


In [ ]:
# Create a NumPy array of shape (2, 4). Print its transpose and reshape it into (4, 2).
import numpy as np

# Create a NumPy array of shape (2, 4)
original_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(f"\nOriginal Array (2, 4):\n{original_array}")

# Print its transpose
transposed_array = original_array.T
print(f"Transposed Array (4, 2):\n{transposed_array}")

# Reshape it into (4, 2)
reshaped_array = original_array.reshape(4, 2)
print(f"Reshaped Array (4, 2):\n{reshaped_array}")



Original Array (2, 4):
[[1 2 3 4]
 [5 6 7 8]]
Transposed Array (4, 2):
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
Reshaped Array (4, 2):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# Write a NumPy program to multiply two 3x3 matrices.
import numpy as np

# Define two 3x3 matrices
matrix_a = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matrix_b = np.array([[9, 8, 7],
                     [6, 5, 4],
                     [3, 2, 1]])

print(f"\nMatrix A:\n{matrix_a}")
print(f"Matrix B:\n{matrix_b}")

# Multiply the two matrices
result_matrix = np.dot(matrix_a, matrix_b)
print(f"Result of Matrix Multiplication:\n{result_matrix}")



Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]
Result of Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
# Write a NumPy program to compute the mean, median, and standard deviation of a random array of 10 integers.
import numpy as np

# Create a random array of 10 integers (e.g., between 1 and 100)
random_integers = np.random.randint(1, 101, size=10)
print(f"\nRandom Array of 10 Integers: {random_integers}")

# Compute mean, median, and standard deviation
mean_value = np.mean(random_integers)
median_value = np.median(random_integers)
std_dev_value = np.std(random_integers)

print(f"Mean: {mean_value}")
print(f"Median: {median_value}")
print(f"Standard Deviation: {std_dev_value}")



Random Array of 10 Integers: [24 28  5 13 20 79 59 67 51 13]
Mean: 35.9
Median: 26.0
Standard Deviation: 24.59044529893674


D.PANDAS

In [ ]:
import pandas as pd

# Create a list of 10 integers
my_list = [15, 22, 8, 30, 5, 12, 28, 10, 18, 25]

# Convert the list to a Pandas Series
s = pd.Series(my_list)

# Calculate sum, average, maximum, and minimum
list_sum = s.sum()
list_average = s.mean()
list_maximum = s.max()
list_minimum = s.min()

print(f"List: {my_list}")
print(f"Sum: {list_sum}")
print(f"Average: {list_average}")
print(f"Maximum: {list_maximum}")
print(f"Minimum: {list_minimum}")


List: [15, 22, 8, 30, 5, 12, 28, 10, 18, 25]
Sum: 173
Average: 17.3
Maximum: 30
Minimum: 5


In [ ]:
import pandas as pd

# Create a tuple of 5 city names
city_tuple = ("London", "Paris", "Rome", "Tokyo", "Berlin")

# Convert the tuple to a Pandas Series
s_cities = pd.Series(city_tuple)

# Reverse the Series using slicing and convert back to tuple for output clarity
reversed_cities_series = s_cities[::-1]

print(f"Original Tuple: {city_tuple}")
print(f"Reversed Cities (as Pandas Series): {reversed_cities_series}")


Original Tuple: ('London', 'Paris', 'Rome', 'Tokyo', 'Berlin')
Reversed Cities (as Pandas Series): 4    Berlin
3     Tokyo
2      Rome
1     Paris
0    London
dtype: object


In [ ]:
import pandas as pd

# Create a list with duplicate numbers
numbers_with_duplicates = [10, 20, 10, 30, 40, 20, 50, 40]

# Convert the list to a Pandas Series and then remove duplicates
s_unique = pd.Series(numbers_with_duplicates).drop_duplicates()

# Convert back to a list if required for output format
unique_numbers_list = s_unique.tolist()

print(f"Original List: {numbers_with_duplicates}")
print(f"List with Duplicates Removed (using Pandas): {unique_numbers_list}")


Original List: [10, 20, 10, 30, 40, 20, 50, 40]
List with Duplicates Removed (using Pandas): [10, 20, 30, 40, 50]


In [ ]:
import pandas as pd

# Create a dictionary of student names and marks
student_marks_dict = {
    "Alice": 85,
    "Bob": 92,
    "Charlie": 78,
    "David": 92,
    "Eve": 89,
}

# Convert the dictionary to a Pandas DataFrame
df_students = pd.DataFrame(
    list(student_marks_dict.items()), columns=["Student Name", "Marks"]
)

# Find the student(s) with the highest marks
highest_marks = df_students["Marks"].max()
students_with_highest_marks = df_students[
    df_students["Marks"] == highest_marks
]["Student Name"].tolist()

print(f"Student Marks: {student_marks_dict}")
print(f"Student(s) with the highest marks: {students_with_highest_marks}")


Student Marks: {'Alice': 85, 'Bob': 92, 'Charlie': 78, 'David': 92, 'Eve': 89}
Student(s) with the highest marks: ['Bob', 'David']


In [ ]:
import pandas as pd

# Define the string
my_string = "programming"

# Convert the string into a list of characters and then to a Pandas Series
s_chars = pd.Series(list(my_string))

# Count the frequency of each character
char_frequency = s_chars.value_counts()

print(f"String: '{my_string}'")
print(f"Character Frequency (as Pandas Series):\n{char_frequency}")


String: 'programming'
Character Frequency (as Pandas Series):
r    2
g    2
m    2
p    1
o    1
a    1
i    1
n    1
Name: count, dtype: int64
