<a href="https://colab.research.google.com/github/Subhranshu-123/BIKE2/blob/main/Copy_of_encoding%2C_feature_scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
# Sample DataFrame with a categorical column
data = {'Category': ['Red', 'Green', 'Blue', 'Green', 'Red']}
df = pd.DataFrame(data)
label_encoder = LabelEncoder()
df['Category_LabelEncoded'] = label_encoder.fit_transform(df['Category'])
print("Original DataFrame:")
print(df[['Category']])

print("\nDataFrame after Label Encoding:")
print(df)


Original DataFrame:
  Category
0      Red
1    Green
2     Blue
3    Green
4      Red

DataFrame after Label Encoding:
  Category  Category_LabelEncoded
0      Red                      2
1    Green                      1
2     Blue                      0
3    Green                      1
4      Red                      2


In [ ]:
decoded_labels = label_encoder.inverse_transform(df['Category_LabelEncoded'])
print("\nDecoded Labels:", decoded_labels)



Decoded Labels: ['Red' 'Green' 'Blue' 'Green' 'Red']


In [ ]:
import pandas as pd

data = {'color': ['red', 'blue', 'red', 'green', 'blue']}
df = pd.DataFrame(data)

# One-hot encode the 'color' column
df_encoded = pd.get_dummies(df, columns=['color'])

print(df_encoded)

   color_blue  color_green  color_red
0       False        False       True
1        True        False      False
2       False        False       True
3       False         True      False
4        True        False      False


In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Sample categorical data
data = np.array([['red'], ['green'], ['blue'], ['red']])

# Initialize OneHotEncoder
encoder = OneHotEncoder(sparse_output=False) # Set sparse_output=False for dense array output

# Fit and transform the data
encoded_data = encoder.fit_transform(data)

print(encoded_data)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

# Sample dataset
data = {
    'Feature_1': [10, 20, 30, 40, 50, 100],
    'Feature_2': [0.1, 0.5, 1.2, 2.5, 5.0, 15.0],
    'Target': [0, 1, 0, 1, 0, 1]
}
df = pd.DataFrame(data)

# Split data into training and testing sets (Crucial step to avoid data leakage)
X = df[['Feature_1', 'Feature_2']]
y = df['Target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# 1. Standardization (Z-score normalization)
# Scales data to have a mean of 0 and a standard deviation of 1.
scaler_standard = StandardScaler()
X_train_scaled_standard = scaler_standard.fit_transform(X_train) # Fit only on training data
X_test_scaled_standard = scaler_standard.transform(X_test) # Transform both using the fitted scaler

# 2. Min-Max Scaling (Normalization)
# Scales features to a specific range, usually between 0 and 1.
scaler_minmax = MinMaxScaler()
X_train_scaled_minmax = scaler_minmax.fit_transform(X_train)
X_test_scaled_minmax = scaler_minmax.transform(X_test)

# 3. Robust Scaling
# Scales data using the median and interquartile range (IQR), making it robust to outliers.
scaler_robust = RobustScaler()
X_train_scaled_robust = scaler_robust.fit_transform(X_train)
X_test_scaled_robust = scaler_robust.transform(X_test)

# The original response included print statements to show the data and verify scaling results.
# You can find the full code and output demonstrating these steps in the referenced documents.
print(scaler_standard.inverse_transform(X_train_scaled_standard))
print(scaler_minmax.inverse_transform(X_train_scaled_minmax))
print(scaler_robust.inverse_transform(X_train_scaled_robust))

[[100.   15. ]
 [ 30.    1.2]
 [ 50.    5. ]
 [ 40.    2.5]]
[[100.   15. ]
 [ 30.    1.2]
 [ 50.    5. ]
 [ 40.    2.5]]
[[100.   15. ]
 [ 30.    1.2]
 [ 50.    5. ]
 [ 40.    2.5]]
