<a href="https://colab.research.google.com/github/Subhranshu-123/BIKE2/blob/main/Copy_of_feature_engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Assuming df is your DataFrame
missing_values_count = df.isnull().sum()
print("Missing values per column:\n", missing_values_count)

# To see the percentage of missing values
missing_values_percentage = (df.isnull().sum() / len(df)) * 100
print("\nPercentage of missing values per column:\n", missing_values_percentage)

Missing values per column:
 col1    1
col2    1
col3    1
dtype: int64

Percentage of missing values per column:
 col1    20.0
col2    20.0
col3    20.0
dtype: float64


In [ ]:
df_cleaned_rows = df.dropna()



In [ ]:
# Load a sample DataFrame (replace this with your actual data loading code)
data = {'col1': [1, 2, 3, None, 5],
        'col2': ['A', 'B', None, 'D', 'E'],
        'col3': [True, False, True, False, None]}
df = pd.DataFrame(data)

display(df)

col1  col2   col3
0   1.0     A   True
1   2.0     B  False
2   3.0  None   True
3   NaN     D  False
4   5.0     E   None

In [ ]:
df_cleaned_cols = df.drop(columns=['col3'])

In [ ]:
# Impute with mean
df['col1'].fillna(df['col1'].mean(), inplace=True)
# Impute with median
df['col1'].fillna(df['col1'].median(), inplace=True)

/tmp/ipython-input-2648279318.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['col1'].fillna(df['col1'].mean(), inplace=True)
/tmp/ipython-input-2648279318.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try 

In [ ]:
# Impute with mode
df['col2'].fillna(df['col2'].mode()[0], inplace=True)

/tmp/ipython-input-484865605.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['col2'].fillna(df['col2'].mode()[0], inplace=True)


In [ ]:
df['col3'].fillna(method='ffill', inplace=True)
df['col3'].fillna(method='bfill', inplace=True)

/tmp/ipython-input-1363279192.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['col3'].fillna(method='ffill', inplace=True)
/tmp/ipython-input-1363279192.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['col3'].fillna(method='ffill', inplace=True)
/tmp/ipython-input-1363279192.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_obje

In [ ]:
from sklearn.impute import KNNImputer

imputer = KNNImputer(n_neighbors=5)
df_imputed = pd.DataFrame(imputer.fit_transform(df[['col1']]), columns=['col1'])

In [ ]:
df['col1_missing'] = df['col1'].isnull().astype(int)

In [1]:
import pandas as pd

df1 = pd.DataFrame({'A': [1, 2, 3], 'B': ['x', 'y', 'z']}, index=['idx1', 'idx2', 'idx3'])
df2 = pd.DataFrame({'C': [4, 5], 'D': ['a', 'b']}, index=['idx1', 'idx3'])

# Perform a left join based on index
result_df = df1.join(df2)
print(result_df)

      A  B    C    D
idx1  1  x  4.0    a
idx2  2  y  NaN  NaN
idx3  3  z  5.0    b


In [3]:
# Merge df1 and df2 based on their index
merged_df = pd.merge(df1, df2, left_index=True, right_index=True, how='inner')
display(merged_df)

A  B  C  D
idx1  1  x  4  a
idx3  3  z  5  b

In [4]:
pd.concat([df1, df2], axis=0)


A    B    C    D
idx1  1.0    x  NaN  NaN
idx2  2.0    y  NaN  NaN
idx3  3.0    z  NaN  NaN
idx1  NaN  NaN  4.0    a
idx3  NaN  NaN  5.0    b

In [5]:
pd.concat([df1, df2], axis=1)

A  B    C    D
idx1  1  x  4.0    a
idx2  2  y  NaN  NaN
idx3  3  z  5.0    b

In [9]:
df1.join(df2, how='left')


A  B    C    D
idx1  1  x  4.0    a
idx2  2  y  NaN  NaN
idx3  3  z  5.0    b

In [10]:
df1.join(df2, how='right')

A  B  C  D
idx1  1  x  4  a
idx3  3  z  5  b

In [11]:
df1.join(df2, how='inner')

A  B  C  D
idx1  1  x  4  a
idx3  3  z  5  b

In [12]:
df1.join(df2, how='outer')

A  B    C    D
idx1  1  x  4.0    a
idx2  2  y  NaN  NaN
idx3  3  z  5.0    b

ENCODING

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df1['encoded_column'] = le.fit_transform(df1['B'])

In [18]:
    import pandas as pd
    data_encoded = pd.get_dummies(df1, columns=['B'], prefix='category')

In [21]:
    from sklearn.preprocessing import OneHotEncoder
    ohe = OneHotEncoder(sparse_output=False)
    encoded_array = ohe.fit_transform(df1[['B']])
    # Convert to DataFrame if needed
    encoded_df = pd.DataFrame(encoded_array, columns=ohe.get_feature_names_out(['B']))

In [23]:
from sklearn.preprocessing import OrdinalEncoder
# Define the order of categories - assuming a meaningful order for 'B'
category_order = [['x', 'y', 'z']]
oe = OrdinalEncoder(categories=category_order)
df1['encoded_column'] = oe.fit_transform(df1[['B']])
display(df1)

A  B  encoded_column
idx1  1  x             0.0
idx2  2  y             1.0
idx3  3  z             2.0

NUMERICAL FEATURE TRANFORM MINMAX SCALER, STANDARD SCALER, ROBUST SCALER

In [24]:
    from sklearn.preprocessing import StandardScaler
    import numpy as np

    data = np.array([[10, 200], [20, 300], [30, 400]])
    scaler = StandardScaler()
    scaled_data = scaler.fit_transform(data)
    print(scaled_data)

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


In [25]:
    from sklearn.preprocessing import MinMaxScaler
    import numpy as np

    data = np.array([[10, 200], [20, 300], [30, 400]])
    scaler = MinMaxScaler()
    scaled_data = scaler.fit_transform(data)
    print(scaled_data)

[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


In [26]:
    from sklearn.preprocessing import RobustScaler
    import numpy as np

    data = np.array([[10, 200], [20, 300], [30, 400], [1000, 5000]]) # Added an outlier
    scaler = RobustScaler()
    scaled_data = scaler.fit_transform(data)
    print(scaled_data)

[[-0.05882353 -0.11764706]
 [-0.01960784 -0.03921569]
 [ 0.01960784  0.03921569]
 [ 3.82352941  3.64705882]]


binning

In [27]:
    import pandas as pd
    data = {'age': [10, 25, 30, 45, 60, 75, 80, 95]}
    df = pd.DataFrame(data)
    bins = [0, 20, 40, 60, 80, 100]
    labels = ['0-20', '21-40', '41-60', '61-80', '81-100']
    df['age_binned'] = pd.cut(df['age'], bins=bins, labels=labels, right=False)
    print(df)

   age age_binned
0   10       0-20
1   25      21-40
2   30      21-40
3   45      41-60
4   60      61-80
5   75      61-80
6   80     81-100
7   95     81-100


DISCRETIZATION

In [28]:
from sklearn.preprocessing import KBinsDiscretizer
import numpy as np
import pandas as pd

# Sample Data
data = {'Age': [10, 25, 30, 45, 55, 60, 75, 80, 90]}
df = pd.DataFrame(data)

# Reshape the data for KBinsDiscretizer (requires 2D array)
age_data = df[['Age']].values

# Equal-width discretization
discretizer_uniform = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='uniform')
df['Age_SKL_Uniform'] = discretizer_uniform.fit_transform(age_data)

# Equal-frequency (quantile) discretization
discretizer_quantile = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='quantile')
df['Age_SKL_Quantile'] = discretizer_quantile.fit_transform(age_data)

print(df)

   Age  Age_SKL_Uniform  Age_SKL_Quantile
0   10              0.0               0.0
1   25              0.0               0.0
2   30              0.0               0.0
3   45              1.0               1.0
4   55              1.0               1.0
5   60              1.0               1.0
6   75              2.0               2.0
7   80              2.0               2.0
8   90              2.0               2.0


In [29]:
import pandas as pd

# Sample Data
data = {'Age': [10, 25, 30, 45, 55, 60, 75, 80, 90]}
df = pd.DataFrame(data)

# Discretize 'Age' into 3 equal-frequency bins
df['Age_EqualFreq_Bins'] = pd.qcut(df['Age'], q=3)
print(df)

   Age Age_EqualFreq_Bins
0   10      (9.999, 40.0]
1   25      (9.999, 40.0]
2   30      (9.999, 40.0]
3   45       (40.0, 65.0]
4   55       (40.0, 65.0]
5   60       (40.0, 65.0]
6   75       (65.0, 90.0]
7   80       (65.0, 90.0]
8   90       (65.0, 90.0]


In [30]:
import pandas as pd

# Sample Data
data = {'Age': [10, 25, 30, 45, 55, 60, 75, 80, 90]}
df = pd.DataFrame(data)

# Discretize 'Age' into 3 equal-width bins
df['Age_EqualWidth_Bins'] = pd.cut(df['Age'], bins=3)
print(df)

   Age Age_EqualWidth_Bins
0   10      (9.92, 36.667]
1   25      (9.92, 36.667]
2   30      (9.92, 36.667]
3   45    (36.667, 63.333]
4   55    (36.667, 63.333]
5   60    (36.667, 63.333]
6   75      (63.333, 90.0]
7   80      (63.333, 90.0]
8   90      (63.333, 90.0]


logarithmic/power transformation

In [31]:
import numpy as np
import pandas as pd

# Sample data with a right-skewed distribution
data = pd.Series([1, 5, 10, 20, 50, 100, 250, 500, 1000])

# Apply natural logarithm transformation
log_transformed_data_natural = np.log(data)

# Apply base-10 logarithm transformation
log_transformed_data_base10 = np.log10(data)

# To handle zero or negative values, add a small constant before logging
data_with_zero = pd.Series([0, 1, 5, 10, 50])
log_transformed_data_plus_one = np.log1p(data_with_zero) # equivalent to np.log(data_with_zero + 1)

print("Original Data:\n", data)
print("\nNatural Log Transformed Data:\n", log_transformed_data_natural)
print("\nBase-10 Log Transformed Data:\n", log_transformed_data_base10)
print("\nLog Transformed Data (with +1 for zeros):\n", log_transformed_data_plus_one)

Original Data:
 0       1
1       5
2      10
3      20
4      50
5     100
6     250
7     500
8    1000
dtype: int64

Natural Log Transformed Data:
 0    0.000000
1    1.609438
2    2.302585
3    2.995732
4    3.912023
5    4.605170
6    5.521461
7    6.214608
8    6.907755
dtype: float64

Base-10 Log Transformed Data:
 0    0.00000
1    0.69897
2    1.00000
3    1.30103
4    1.69897
5    2.00000
6    2.39794
7    2.69897
8    3.00000
dtype: float64

Log Transformed Data (with +1 for zeros):
 0    0.000000
1    0.693147
2    1.791759
3    2.397895
4    3.931826
dtype: float64


In [33]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

# Sample data with a single feature
X = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)

# Create PolynomialFeatures object with degree 2
poly = PolynomialFeatures(degree=2)

# Transform the data
X_poly = poly.fit_transform(X)

print(X_poly)

[[ 1.  1.  1.]
 [ 1.  2.  4.]
 [ 1.  3.  9.]
 [ 1.  4. 16.]
 [ 1.  5. 25.]]


In [32]:
from sklearn.preprocessing import PowerTransformer
import numpy as np
import pandas as pd

# Sample data
data = pd.DataFrame({'value': [1, 5, 10, 20, 50, 100, 250, 500, 1000]})

# Instantiate PowerTransformer with Box-Cox (requires positive data)
# For data that can contain zeros or negative values, use 'yeo-johnson'
pt_boxcox = PowerTransformer(method='box-cox', standardize=False)

# Fit and transform the data
boxcox_transformed_data = pt_boxcox.fit_transform(data[['value']])
data['boxcox_transformed'] = boxcox_transformed_data

# Instantiate PowerTransformer with Yeo-Johnson (handles positive, zero, and negative data)
pt_yeojohnson = PowerTransformer(method='yeo-johnson', standardize=False)

# Fit and transform the data
yeojohnson_transformed_data = pt_yeojohnson.fit_transform(data[['value']])
data['yeojohnson_transformed'] = yeojohnson_transformed_data

print("Original Data:\n", data[['value']])
print("\nBox-Cox Transformed Data:\n", data[['boxcox_transformed']])
print("\nYeo-Johnson Transformed Data:\n", data[['yeojohnson_transformed']])

Original Data:
    value
0      1
1      5
2     10
3     20
4     50
5    100
6    250
7    500
8   1000

Box-Cox Transformed Data:
    boxcox_transformed
0            0.000000
1            1.681619
2            2.452221
3            3.252283
4            4.357039
5            5.229921
6            6.435231
7            7.387562
8            8.376300

Yeo-Johnson Transformed Data:
    yeojohnson_transformed
0                0.695685
1                1.808784
2                2.428452
3                3.093894
4                4.014428
5                4.729203
6                5.689508
7                6.424780
8                7.166499


polynomial feature

In [34]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

# Sample data with a single feature
X = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)

# Create PolynomialFeatures object with degree 2
poly = PolynomialFeatures(degree=2)

# Transform the data
X_poly = poly.fit_transform(X)

print(X_poly)

[[ 1.  1.  1.]
 [ 1.  2.  4.]
 [ 1.  3.  9.]
 [ 1.  4. 16.]
 [ 1.  5. 25.]]


outlier treatmesnt

In [35]:
        from scipy.stats import zscore
        import numpy as np

        data = np.array([1, 2, 3, 4, 100, 5, 6, 7])
        z_scores = np.abs(zscore(data))
        outliers = data[z_scores > 2]

In [36]:
        import numpy as np

        data = np.array([1, 2, 3, 4, 100, 5, 6, 7])
        Q1 = np.percentile(data, 25)
        Q3 = np.percentile(data, 75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        outliers = data[(data < lower_bound) | (data > upper_bound)]

outlier detection

In [37]:
from sklearn.ensemble import IsolationForest
import numpy as np

# Sample data
X = np.array([[1, 1], [1.1, 1.1], [1.2, 1.2], [10, 10], [1.3, 1.3]])

# Create an Isolation Forest model
model = IsolationForest(random_state=42)

# Fit the model and predict outliers (returns -1 for outliers, 1 for inliers)
predictions = model.fit_predict(X)

print(predictions)

[ 1  1  1 -1  1]


In [38]:
from sklearn.neighbors import LocalOutlierFactor
import numpy as np

# Sample data
X = np.array([[1, 1], [1.1, 1.1], [1.2, 1.2], [10, 10], [1.3, 1.3]])

# Create a Local Outlier Factor model
# 'contamination' parameter estimates the proportion of outliers in the data
model = LocalOutlierFactor(n_neighbors=2, contamination=0.1)

# Fit the model and predict outliers (returns -1 for outliers, 1 for inliers)
predictions = model.fit_predict(X)

print(predictions)

[ 1  1  1 -1  1]


In [39]:
from sklearn.svm import OneClassSVM
import numpy as np

# Sample data
X = np.array([[1, 1], [1.1, 1.1], [1.2, 1.2], [10, 10], [1.3, 1.3]])

# Create a One-Class SVM model
# 'nu' parameter represents the upper bound on the fraction of training errors and a lower bound of the fraction of support vectors
model = OneClassSVM(gamma='auto', nu=0.1)

# Fit the model and predict outliers (returns -1 for outliers, 1 for inliers)
predictions = model.fit_predict(X)

print(predictions)

[-1  1  1  1  1]


outlier capping

In [40]:
    import pandas as pd
    import numpy as np

    # Sample DataFrame
    data = {'value': [10, 20, 30, 40, 50, 100, 5, 120, 150, 200, 250, 300]}
    df = pd.DataFrame(data)

    # Define lower and upper percentiles
    lower_percentile = 5
    upper_percentile = 95

    # Calculate the capping limits
    lower_limit = np.percentile(df['value'], lower_percentile)
    upper_limit = np.percentile(df['value'], upper_percentile)

    # Apply capping using np.clip
    df['value_capped'] = np.clip(df['value'], lower_limit, upper_limit)

    print(df)

    value  value_capped
0      10         10.00
1      20         20.00
2      30         30.00
3      40         40.00
4      50         50.00
5     100        100.00
6       5          7.75
7     120        120.00
8     150        150.00
9     200        200.00
10    250        250.00
11    300        272.50


In [41]:
    import pandas as pd
    import numpy as np

    # Sample DataFrame
    data = {'value': [10, 20, 30, 40, 50, 100, 5, 120, 150, 200, 250, 300]}
    df = pd.DataFrame(data)

    # Calculate Q1, Q3, and IQR
    Q1 = df['value'].quantile(0.25)
    Q3 = df['value'].quantile(0.75)
    IQR = Q3 - Q1

    # Define upper and lower bounds
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Apply capping
    df['value_capped_iqr'] = np.where(df['value'] < lower_bound, lower_bound,
                                      np.where(df['value'] > upper_bound, upper_bound, df['value']))

    print(df)

    value  value_capped_iqr
0      10              10.0
1      20              20.0
2      30              30.0
3      40              40.0
4      50              50.0
5     100             100.0
6       5               5.0
7     120             120.0
8     150             150.0
9     200             200.0
10    250             250.0
11    300             300.0
