<a href="https://colab.research.google.com/github/Subhranshu-123/BIKE2/blob/main/NUMPY_BASICS_BY_SUBHRANSHU(IIT_BHILAI).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
A=np.array([[1,2,3],
             [4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [5]:
A.shape

(2, 3)

In [6]:
A[0]

array([1, 2, 3])

In [7]:
A[1]

array([4, 5, 6])

In [8]:
A[0][0]

np.int64(1)

In [9]:
A[0][2]

np.int64(3)

In [20]:
A.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
A[0][1]

np.int64(2)

In [22]:
A[1][2]#column=vertical #row= horizontal

np.int64(6)

In [23]:
A[1][2]

np.int64(6)

In [24]:
A[1]

array([4, 5, 6])

In [25]:
A[0]=10

In [26]:
A

array([[10, 10, 10],
       [ 4,  5,  6]])

In [28]:
A[0][0]=999
[A]

[array([[999,  10,  10],
        [  4,   5,   6]])]

In [30]:
A[0][2]=2333

In [31]:
A

array([[ 999,   10, 2333],
       [   4,    5,    6]])

In [32]:
A[:2]

array([[ 999,   10, 2333],
       [   4,    5,    6]])

In [33]:
A[:1]


array([[ 999,   10, 2333]])

In [35]:
A[0:2]

array([[ 999,   10, 2333],
       [   4,    5,    6]])

In [38]:
a=([[[1,2,3]
   ,[4,5,6]
   ,[8,9,10]]])

In [39]:
a

[[[1, 2, 3], [4, 5, 6], [8, 9, 10]]]

In [40]:
a[0]

[[1, 2, 3], [4, 5, 6], [8, 9, 10]]

In [42]:
a[:3]

[[[1, 2, 3], [4, 5, 6], [8, 9, 10]]]

In [44]:
a[:2]

[[[1, 2, 3], [4, 5, 6], [8, 9, 10]]]

In [45]:
a=np.array([[[1,2,3]
   ,[4,5,6]
   ,[8,9,10]]])

In [46]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 8,  9, 10]]])

In [49]:
a[0][0]

array([1, 2, 3])

In [50]:
a[0][1]

array([4, 5, 6])

In [51]:
a[0][2]

array([ 8,  9, 10])

In [53]:
a[0][0][0]

np.int64(1)

In [54]:
a[0][0][1]

np.int64(2)

In [55]:
a[0][0][2]

np.int64(3)

In [56]:
a[0][1][0]

np.int64(4)

In [57]:
a[0][1][1]

np.int64(5)

In [58]:
a[0][1][2]

np.int64(6)

In [59]:
a[0][2][0]

np.int64(8)

In [60]:
a[0][2][1]

np.int64(9)

In [61]:
a[0][2][2]

np.int64(10)

In [62]:
type(a)

numpy.ndarray

In [63]:
a[0][2][1] & a[0][2][2]

np.int64(8)

In [64]:
a.ndim

3

In [65]:
len(a.shape)

3

In [66]:
a.size

9

In [67]:
a.shape

(1, 3, 3)

In [68]:
a.dtype

dtype('int64')

In [69]:
import math
a.size == math.prod(a.shape)

True

In [70]:
# HOW TO CREATE BASIC ARRAY
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [71]:
np.ones(11)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [72]:
np.empty(2)

array([-6.49278429e+101,  9.06071993e+247])

In [73]:
np.arange(4)

array([0, 1, 2, 3])

In [74]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [75]:
np.linspace(0,10,num=6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [76]:
np.linspace(0,10,num=8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [77]:
A=np.ones(2,dtype=np.int64)
A

array([1, 1])

In [79]:
# adding, removing,sorting
X=np.array([2,5,6,8,9,19,22,1,0])
X


array([ 2,  5,  6,  8,  9, 19, 22,  1,  0])

In [80]:
np.sort(X)

array([ 0,  1,  2,  5,  6,  8,  9, 19, 22])

In [81]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [83]:
a=np.array([[1,2],[5,6]])
b=np.array([[7,8]])
np.concatenate((a,b),axis=0)

array([[1, 2],
       [5, 6],
       [7, 8]])

In [89]:
Y= np.array([[[1,3,5,6],
             [9,8,12,65]],
            [[5,8,99,98],
            [78,89,90,62]],

            [[5,8,9,33],
             [56,89,99,90]]])


In [90]:
Y

array([[[ 1,  3,  5,  6],
        [ 9,  8, 12, 65]],

       [[ 5,  8, 99, 98],
        [78, 89, 90, 62]],

       [[ 5,  8,  9, 33],
        [56, 89, 99, 90]]])

In [91]:
Y.shape

(3, 2, 4)

In [92]:
Y.size

24

In [93]:
Y.ndim

3

In [99]:
A=np.arange(6)
print(A)

[0 1 2 3 4 5]


In [100]:
b=A.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [104]:
b=np.reshape(A,(3,2),order="F")
b

array([[0, 3],
       [1, 4],
       [2, 5]])

In [105]:
data=np.array([1,2,3])
data

array([1, 2, 3])

In [106]:
data[0:2]

array([1, 2])

In [107]:
data[0:1]

array([1])

In [108]:
data[1:2]

array([2])

In [111]:
data[-1:]

array([3])

In [113]:
print(a[a<3])

[1 2]


In [127]:
a=np.array([[1,2,3,4],
    [5,6,7,8]])
five_up = (a<=5)
print(a[five_up])

[1 2 3 4 5]


In [128]:
D= a[a%2==0]
print(D)

[2 4 6 8]


In [130]:
W = a[(a%2==0) &(a%3==0)]
print(W)

[6]


In [131]:
W = a[(a%2==0) |(a%3==0)]
print(W)

[2 3 4 6 8]


In [132]:
five_up= ((a>5 )|(a==5))
print(five_up)

[[False False False False]
 [ True  True  True  True]]


In [133]:
a=np.nonzero(a<5)
print(a)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [134]:
list= list(zip(a[0],a[1]))
for i in list:
  print(i)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [135]:
id(a)

138382774486464

In [136]:
id(b)

138382775915632

In [137]:
a1= np.array([[1,1],
              [2,2]])
a2= np.array([[33,44],
              [33,44]])

In [138]:
np.vstack((a1,a2))

array([[ 1,  1],
       [ 2,  2],
       [33, 44],
       [33, 44]])

In [139]:
np.hstack((a1,a2))

array([[ 1,  1, 33, 44],
       [ 2,  2, 33, 44]])

In [141]:
b=np.arange(1,25).reshape(2,12)
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [142]:
b=np.arange(1,25).reshape(3,8)

In [143]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [147]:
V=np.hsplit(b,(3,4))
V

[array([[ 1,  2,  3],
        [ 9, 10, 11],
        [17, 18, 19]]),
 array([[ 4],
        [12],
        [20]]),
 array([[ 5,  6,  7,  8],
        [13, 14, 15, 16],
        [21, 22, 23, 24]])]

In [150]:
J=V.copy()
J

[array([[ 1,  2,  3],
        [ 9, 10, 11],
        [17, 18, 19]]),
 array([[ 4],
        [12],
        [20]]),
 array([[ 5,  6,  7,  8],
        [13, 14, 15, 16],
        [21, 22, 23, 24]])]

In [151]:
data=np.array([1,2])
df=np.ones(2,dtype=int)
data+df

array([2, 3])

In [153]:
data-df

array([0, 1])

In [154]:
data*data

array([1, 4])

In [155]:
data*df

array([1, 2])

In [156]:
data/data

array([1., 1.])

In [157]:
data/df

array([1., 2.])

In [158]:
a=np.array([1,2,3,4])
a.sum()

np.int64(10)

In [162]:
b=np.array([[1,2],
            [3,4]])
b.sum(axis=0)

array([4, 6])

In [163]:
b.sum(axis=1)

array([3, 7])

In [164]:
data=np.array([1,2,3,4])
data*1.6

array([1.6, 3.2, 4.8, 6.4])

In [166]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [167]:
data.max()

np.int64(4)

In [168]:
data.min()

np.int64(1)

In [169]:
data.mean()

np.float64(2.5)

In [170]:
data.std()

np.float64(1.118033988749895)

In [172]:
import statistics
data.mean()

np.float64(2.5)

In [173]:
data.sum()

np.int64(10)

In [174]:
data.var()

np.float64(1.25)

In [175]:
np.random.random(3)

array([0.79581061, 0.83534216, 0.28080818])

In [176]:
np.random.randint(3)

2

In [177]:
np.random.randint(3)

2

In [179]:
np.random.random(3)

array([0.70307978, 0.43068155, 0.1646333 ])

In [181]:
a=np.array([11,11,11,11,23,45,67])
unique_values=np.unique(a)
print(unique_values)

[11 23 45 67]


In [183]:
np.count_nonzero(np.isnan(11))

0

In [184]:
a=([[11,12,13,14],
    [13,43,25,66]])
transpose_a=np.transpose(a)
print(transpose_a)

[[11 13]
 [12 43]
 [13 25]
 [14 66]]


In [186]:
z=np.flip(a)
print(z)

[[66 25 43 13]
 [14 13 12 11]]


In [189]:
h=np.flatnonzero(a)
h

array([0, 1, 2, 3, 4, 5, 6, 7])

In [195]:
k=np.save('NUMPY BASICS BY SUBHRANSHU(IIT BHILAI).ipynb',a)
